#!/usr/bin/env python3

import sys

from argParse import ArgumentParser
from model import distance

def main():
    # Parse command line arguments
    parser = ArgumentParser()
    parser.add_argument("str1", help="string to compare")
    parser.add_argument("str2", help="string to compare")
    args = vars(parser.parse_args())

    # Compare files
    d = distances(str1, str2)
    print(d[len(str1)][len(str2)][0])


if __name__ == "__main__":
    main()